### ISSUE TITLE
Platform definition php5.3 not compatible

### ISSUE THREAD

**Issue by werrolf** [mapbender/coordinates-utility#6]
I've seen a usage of array_column in the code, which is a new function in PHP5.5.
In composer.json the platform is defined as PHP >= 5.3.0 which is too old, it will not be compatible. Suggestion: platform def in composer.json should be increased to PHP 5.5. This will prevent installation with an appropriate error on old PHP versions.

**Comment by sveta-wl** [comment]
Yes, you are right. The required PHP version has been updated to the proper one.
